version: "3.3"
services:
  envoy:
    image: envoyproxy/envoy-dev:latest
    ports:
      - 127.0.0.1:8001:8001
      - 127.0.0.1:1111:1111
    volumes:
      - ./envoy_conf.yaml:/etc/envoy/envoy.yaml
    network_mode: host

  backend:
    image: nginx:latest
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./nginx_conf.yaml:/etc/nginx/conf.d/default.conf
      - ./data:/data
    network_mode: host


